"""
This type stub file was generated by pyright.
"""

import httpx
from typing import Any, Dict, Generator, Optional, Tuple, Union
from requests.packages.urllib3.util import retry
from google.auth import credentials
from google.auth.transport import requests as google_auth_requests
from firebase_admin._retry import HttpxRetry

"""Internal HTTP client module.

This module provides utilities for making HTTP calls using the requests library.
"""
logger = ...
if hasattr(retry.Retry.DEFAULT, 'allowed_methods'):
    _ANY_METHOD = ...
else:
    _ANY_METHOD = ...
DEFAULT_RETRY_CONFIG = ...
DEFAULT_HTTPX_RETRY_CONFIG = ...
DEFAULT_TIMEOUT_SECONDS = ...
METRICS_HEADERS = ...
class HttpClient:
    """Base HTTP client used to make HTTP calls.

    HttpClient maintains an HTTP session, and handles request authentication and retries if
    necessary.
    """
    def __init__(self, credential=..., session=..., base_url=..., headers=..., retries=..., timeout=...) -> None:
        """Creates a new HttpClient instance from the provided arguments.

        If a credential is provided, initializes a new HTTP session authorized with it. If neither
        a credential nor a session is provided, initializes a new unauthorized session.

        Args:
          credential: A Google credential that can be used to authenticate requests (optional).
          session: A custom HTTP session (optional).
          base_url: A URL prefix to be added to all outgoing requests (optional).
          headers: A map of headers to be added to all outgoing requests (optional).
          retries: A urllib retry configuration. Default settings would retry once for low-level
              connection and socket read errors, and up to 4 times for HTTP 500 and 503 errors.
              Pass a False value to disable retries (optional).
          timeout: HTTP timeout in seconds. Defaults to 120 seconds when not specified. Set to
              None to disable timeouts (optional).
        """
        ...
    
    @property
    def session(self): # -> Session | None:
        ...
    
    @property
    def base_url(self): # -> str:
        ...
    
    @property
    def timeout(self): # -> int:
        ...
    
    def parse_body(self, resp):
        ...
    
    def request(self, method, url, **kwargs): # -> Response:
        """Makes an HTTP call using the Python requests library.

        This is the sole entry point to the requests library. All other helper methods in this
        class call this method to send HTTP requests out. Refer to
        http://docs.python-requests.org/en/master/api/ for more information on supported options
        and features.

        Args:
          method: HTTP method name as a string (e.g. get, post).
          url: URL of the remote endpoint.
          **kwargs: An additional set of keyword arguments to be passed into the requests API
              (e.g. json, params, timeout).

        Returns:
          Response: An HTTP response object.

        Raises:
          RequestException: Any requests exceptions encountered while making the HTTP call.
        """
        ...
    
    def headers(self, method, url, **kwargs): # -> CaseInsensitiveDict[str]:
        ...
    
    def body_and_response(self, method, url, **kwargs): # -> tuple[Any, Response | Any]:
        ...
    
    def body(self, method, url, **kwargs):
        ...
    
    def headers_and_body(self, method, url, **kwargs): # -> tuple[CaseInsensitiveDict[str] | Any, Any]:
        ...
    
    def close(self): # -> None:
        ...
    


class JsonHttpClient(HttpClient):
    """An HTTP client that parses response messages as JSON."""
    def __init__(self, **kwargs) -> None:
        ...
    
    def parse_body(self, resp):
        ...
    


class GoogleAuthCredentialFlow(httpx.Auth):
    """Google Auth Credential Auth Flow"""
    def __init__(self, credential: credentials.Credentials) -> None:
        ...
    
    def apply_auth_headers(self, request: httpx.Request, auth_request: google_auth_requests.Request) -> None:
        """A helper function that refreshes credentials if needed and mutates the request headers
        to contain access token and any other Google Auth headers."""
        ...
    
    def auth_flow(self, request: httpx.Request) -> Generator[httpx.Request, httpx.Response, None]:
        ...
    


class HttpxAsyncClient:
    """Async HTTP client used to make HTTP/2 calls using HTTPX.

    HttpxAsyncClient maintains an async HTTPX client, handles request authentication, and retries
    if necessary.
    """
    def __init__(self, credential: Optional[credentials.Credentials] = ..., base_url: str = ..., headers: Optional[Union[httpx.Headers, Dict[str, str]]] = ..., retry_config: HttpxRetry = ..., timeout: int = ..., http2: bool = ...) -> None:
        """Creates a new HttpxAsyncClient instance from the provided arguments.

        If a credential is provided, initializes a new async HTTPX client authorized with it.
        Otherwise, initializes a new unauthorized async HTTPX client.

        Args:
            credential: A Google credential that can be used to authenticate requests (optional).
            base_url: A URL prefix to be added to all outgoing requests (optional).
            headers: A map of headers to be added to all outgoing requests (optional).
            retry_config: A HttpxRetry configuration. Default settings would retry up to 4 times for
                HTTP 500 and 503 errors (optional).
            timeout: HTTP timeout in seconds. Defaults to 120 seconds when not specified (optional).
            http2: A boolean indicating if HTTP/2 support should be enabled. Defaults to `True` when
                not specified (optional).
        """
        ...
    
    @property
    def base_url(self): # -> str:
        ...
    
    @property
    def timeout(self): # -> int:
        ...
    
    @property
    def async_client(self): # -> AsyncClient:
        ...
    
    async def request(self, method: str, url: str, **kwargs: Any) -> httpx.Response:
        """Makes an HTTP call using the HTTPX library.

        This is the sole entry point to the HTTPX library. All other helper methods in this
        class call this method to send HTTP requests out. Refer to
        https://www.python-httpx.org/api/ for more information on supported options
        and features.

        Args:
            method: HTTP method name as a string (e.g. get, post).
            url: URL of the remote endpoint.
            **kwargs: An additional set of keyword arguments to be passed into the HTTPX API
                (e.g. json, params, timeout).

        Returns:
            Response: An HTTPX response object.

        Raises:
            HTTPError: Any HTTPX exceptions encountered while making the HTTP call.
            RequestException: Any requests exceptions encountered while making the HTTP call.
        """
        ...
    
    async def headers(self, method: str, url: str, **kwargs: Any) -> httpx.Headers:
        ...
    
    async def body_and_response(self, method: str, url: str, **kwargs: Any) -> Tuple[Any, httpx.Response]:
        ...
    
    async def body(self, method: str, url: str, **kwargs: Any) -> Any:
        ...
    
    async def headers_and_body(self, method: str, url: str, **kwargs: Any) -> Tuple[httpx.Headers, Any]:
        ...
    
    def parse_body(self, resp: httpx.Response) -> Any:
        ...
    
    async def aclose(self) -> None:
        ...
    


