"""
This type stub file was generated by pyright.
"""

import httpx
from typing import Any, List, Optional, Tuple

"""Internal retry logic module

This module provides utilities for adding retry logic to HTTPX requests
"""
logger = ...
class HttpxRetry:
    """HTTPX based retry config"""
    RETRY_AFTER_STATUS_CODES = ...
    DEFAULT_BACKOFF_MAX = ...
    def __init__(self, max_retries: int = ..., status_forcelist: Optional[List[int]] = ..., backoff_factor: float = ..., backoff_max: float = ..., backoff_jitter: float = ..., history: Optional[List[Tuple[httpx.Request, Optional[httpx.Response], Optional[Exception]]]] = ..., respect_retry_after_header: bool = ...) -> None:
        ...
    
    def copy(self) -> HttpxRetry:
        """Creates a deep copy of this instance."""
        ...
    
    def is_retryable_response(self, response: httpx.Response) -> bool:
        """Determine if a response implies that the request should be retried if possible."""
        ...
    
    def is_exhausted(self) -> bool:
        """Determine if there are anymore more retires."""
        ...
    
    def get_retry_after(self, response: httpx.Response) -> float | None:
        """Determine the Retry-After time needed before sending the next request."""
        ...
    
    def get_backoff_time(self): # -> float | Literal[0]:
        """Determine the backoff time needed before sending the next request."""
        ...
    
    async def sleep_for_backoff(self) -> None:
        """Determine and wait the backoff time needed before sending the next request."""
        ...
    
    async def sleep(self, response: httpx.Response) -> None:
        """Determine and wait the time needed before sending the next request."""
        ...
    
    def increment(self, request: httpx.Request, response: Optional[httpx.Response] = ..., error: Optional[Exception] = ...) -> None:
        """Update the retry state based on request attempt."""
        ...
    


class HttpxRetryTransport(httpx.AsyncBaseTransport):
    """HTTPX transport with retry logic."""
    DEFAULT_RETRY = ...
    def __init__(self, retry: HttpxRetry = ..., **kwargs: Any) -> None:
        ...
    
    async def handle_async_request(self, request: httpx.Request) -> httpx.Response:
        ...
    
    async def aclose(self) -> None:
        ...
    


