"""
This type stub file was generated by pyright.
"""

import google.auth
import httpx
from typing import Callable, Optional
from firebase_admin import exceptions

"""Internal utilities common to all modules."""
_ERROR_CODE_TO_EXCEPTION_TYPE = ...
_HTTP_STATUS_TO_ERROR_CODE = ...
_RPC_CODE_TO_ERROR_CODE = ...
def get_metrics_header(): # -> str:
    ...

def get_app_service(app, name, initializer):
    ...

def handle_platform_error_from_requests(error, handle_func=...): # -> DeadlineExceededError | UnavailableError | UnknownError:
    """Constructs a ``FirebaseError`` from the given requests error.

    This can be used to handle errors returned by Google Cloud Platform (GCP) APIs.

    Args:
        error: An error raised by the requests module while making an HTTP call to a GCP API.
        handle_func: A function that can be used to handle platform errors in a custom way. When
            specified, this function will be called with three arguments. It has the same
            signature as ```_handle_func_requests``, but may return ``None``.

    Returns:
        FirebaseError: A ``FirebaseError`` that can be raised to the user code.
    """
    ...

def handle_platform_error_from_httpx(error: httpx.HTTPError, handle_func: Optional[Callable[..., Optional[exceptions.FirebaseError]]] = ...) -> exceptions.FirebaseError:
    """Constructs a ``FirebaseError`` from the given httpx error.

    This can be used to handle errors returned by Google Cloud Platform (GCP) APIs.

    Args:
        error: An error raised by the httpx module while making an HTTP call to a GCP API.
        handle_func: A function that can be used to handle platform errors in a custom way. When
            specified, this function will be called with three arguments. It has the same
            signature as ```_handle_func_httpx``, but may return ``None``.

    Returns:
        FirebaseError: A ``FirebaseError`` that can be raised to the user code.
    """
    ...

def handle_operation_error(error): # -> UnknownError:
    """Constructs a ``FirebaseError`` from the given operation error.

    Args:
        error: An error returned by a long running operation.

    Returns:
        FirebaseError: A ``FirebaseError`` that can be raised to the user code.
    """
    ...

def handle_requests_error(error, message=..., code=...): # -> DeadlineExceededError | UnavailableError | UnknownError:
    """Constructs a ``FirebaseError`` from the given requests error.

    This method is agnostic of the remote service that produced the error, whether it is a GCP
    service or otherwise. Therefore, this method does not attempt to parse the error response in
    any way.

    Args:
        error: An error raised by the requests module while making an HTTP call.
        message: A message to be included in the resulting ``FirebaseError`` (optional). If not
            specified the string representation of the ``error`` argument is used as the message.
        code: A GCP error code that will be used to determine the resulting error type (optional).
            If not specified the HTTP status code on the error response is used to determine a
            suitable error code.

    Returns:
        FirebaseError: A ``FirebaseError`` that can be raised to the user code.
    """
    ...

def handle_httpx_error(error: httpx.HTTPError, message=..., code=...) -> exceptions.FirebaseError:
    """Constructs a ``FirebaseError`` from the given httpx error.

    This method is agnostic of the remote service that produced the error, whether it is a GCP
    service or otherwise. Therefore, this method does not attempt to parse the error response in
    any way.

    Args:
        error: An error raised by the httpx module while making an HTTP call.
        message: A message to be included in the resulting ``FirebaseError`` (optional). If not
            specified the string representation of the ``error`` argument is used as the message.
        code: A GCP error code that will be used to determine the resulting error type (optional).
            If not specified the HTTP status code on the error response is used to determine a
            suitable error code.

    Returns:
        FirebaseError: A ``FirebaseError`` that can be raised to the user code.
    """
    ...

class EmulatorAdminCredentials(google.auth.credentials.Credentials):
    """ Credentials for use with the firebase local emulator.

    This is used instead of user-supplied credentials or ADC.  It will silently do nothing when
    asked to refresh credentials.
    """
    def __init__(self) -> None:
        ...
    
    def refresh(self, request): # -> None:
        ...
    


