"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict

"""Firebase App Check module."""
_APP_CHECK_ATTRIBUTE = ...
def verify_token(token: str, app=...) -> Dict[str, Any]:
    """Verifies a Firebase App Check token.

    Args:
        token: A token from App Check.
        app: An App instance (optional).

    Returns:
        Dict[str, Any]: The token's decoded claims.

    Raises:
        ValueError: If the app's ``project_id`` is invalid or unspecified,
        or if the token's headers or payload are invalid.
        PyJWKClientError: If PyJWKClient fails to fetch a valid signing key.
    """
    ...

class _AppCheckService:
    """Service class that implements Firebase App Check functionality."""
    _APP_CHECK_ISSUER = ...
    _JWKS_URL = ...
    _project_id = ...
    _scoped_project_id = ...
    _jwks_client = ...
    _APP_CHECK_HEADERS = ...
    def __init__(self, app) -> None:
        ...
    
    def verify_token(self, token: str) -> Dict[str, Any]:
        """Verifies a Firebase App Check token."""
        ...
    


class _Validators:
    """A collection of data validation utilities.

    Methods provided in this class raise ``ValueErrors`` if any validations fail.
    """
    @classmethod
    def check_string(cls, label: str, value: Any): # -> None:
        """Checks if the given value is a string."""
        ...
    


