"""
This type stub file was generated by pyright.
"""

from typing import Optional
from firebase_admin import App
from google.cloud import firestore

"""Cloud Firestore module.

This module contains utilities for accessing the Google Cloud Firestore databases associated with
Firebase apps. This requires the ``google-cloud-firestore`` Python module.
"""
existing = ...
_FIRESTORE_ATTRIBUTE = ...
def client(app: Optional[App] = ..., database_id: Optional[str] = ...) -> firestore.Client:
    """Returns a client that can be used to interact with Google Cloud Firestore.

    Args:
        app: An App instance (optional).
        database_id: The database ID of the Google Cloud Firestore database to be used.
            Defaults to the default Firestore database ID if not specified or an empty string
            (optional).

    Returns:
        google.cloud.firestore.Firestore: A `Firestore Client`_.

    Raises:
        ValueError: If the specified database ID is not a valid string, or if a project ID is not
            specified either via options, credentials or environment variables, or if the specified
            project ID is not a valid string.

    .. _Firestore Client: https://cloud.google.com/python/docs/reference/firestore/latest/\
        google.cloud.firestore_v1.client.Client
    """
    ...

class _FirestoreService:
    """Service that maintains a collection of firestore clients."""
    def __init__(self, app: App) -> None:
        ...
    
    def get_client(self, database_id: Optional[str]) -> firestore.Client:
        """Creates a client based on the database_id. These clients are cached."""
        ...
    


