"""
This type stub file was generated by pyright.
"""

"""Firebase Instance ID module.

This module enables deleting instance IDs associated with Firebase projects.
"""
_IID_SERVICE_URL = ...
_IID_ATTRIBUTE = ...
def delete_instance_id(instance_id, app=...): # -> None:
    """Deletes the specified instance ID and the associated data from Firebase.

    Note that Google Analytics for Firebase uses its own form of Instance ID to
    keep track of analytics data. Therefore deleting a regular Instance ID does
    not delete Analytics data. See `Delete an Instance ID`_ for more information.

    Args:
      instance_id: A non-empty instance ID string.
      app: An App instance (optional).

    Raises:
      InstanceIdError: If an error occurs while invoking the backend instance ID service.
      ValueError: If the specified instance ID or app is invalid.

    .. _Delete an Instance ID: https://firebase.google.com/support/privacy\
          /manage-iids#delete_an_instance_id
    """
    ...

class _InstanceIdService:
    """Provides methods for interacting with the remote instance ID service."""
    error_codes = ...
    def __init__(self, app) -> None:
        ...
    
    def delete_instance_id(self, instance_id): # -> None:
        ...
    


