"""
This type stub file was generated by pyright.
"""

from typing import Dict, Literal, Optional, Union
from enum import Enum
from firebase_admin import App

"""Firebase Remote Config Module.
This module has required APIs for the clients to use Firebase Remote Config with python.
"""
logger = ...
_REMOTE_CONFIG_ATTRIBUTE = ...
MAX_CONDITION_RECURSION_DEPTH = ...
ValueSource = Literal['default', 'remote', 'static']
class PercentConditionOperator(Enum):
    """Enum representing the available operators for percent conditions.
    """
    LESS_OR_EQUAL = ...
    GREATER_THAN = ...
    BETWEEN = ...
    UNKNOWN = ...


class CustomSignalOperator(Enum):
    """Enum representing the available operators for custom signal conditions.
    """
    STRING_CONTAINS = ...
    STRING_DOES_NOT_CONTAIN = ...
    STRING_EXACTLY_MATCHES = ...
    STRING_CONTAINS_REGEX = ...
    NUMERIC_LESS_THAN = ...
    NUMERIC_LESS_EQUAL = ...
    NUMERIC_EQUAL = ...
    NUMERIC_NOT_EQUAL = ...
    NUMERIC_GREATER_THAN = ...
    NUMERIC_GREATER_EQUAL = ...
    SEMANTIC_VERSION_LESS_THAN = ...
    SEMANTIC_VERSION_LESS_EQUAL = ...
    SEMANTIC_VERSION_EQUAL = ...
    SEMANTIC_VERSION_NOT_EQUAL = ...
    SEMANTIC_VERSION_GREATER_THAN = ...
    SEMANTIC_VERSION_GREATER_EQUAL = ...
    UNKNOWN = ...


class _ServerTemplateData:
    """Parses, validates and encapsulates template data and metadata."""
    def __init__(self, template_data) -> None:
        """Initializes a new ServerTemplateData instance.

        Args:
            template_data: The data to be parsed for getting the parameters and conditions.

        Raises:
            ValueError: If the template data is not valid.
        """
        ...
    
    @property
    def parameters(self): # -> dict[Any, Any]:
        ...
    
    @property
    def etag(self): # -> str:
        ...
    
    @property
    def version(self): # -> str:
        ...
    
    @property
    def conditions(self): # -> list[Any]:
        ...
    
    @property
    def template_data_json(self): # -> str:
        ...
    


class ServerTemplate:
    """Represents a Server Template with implementations for loading and evaluating the template."""
    def __init__(self, app: App = ..., default_config: Optional[Dict[str, str]] = ...) -> None:
        """Initializes a ServerTemplate instance.

        Args:
          app: App instance to be used. This is optional and the default app instance will
                be used if not present.
          default_config: The default config to be used in the evaluated config.
        """
        ...
    
    async def load(self): # -> None:
        """Fetches the server template and caches the data."""
        ...
    
    def evaluate(self, context: Optional[Dict[str, Union[str, int]]] = ...) -> ServerConfig:
        """Evaluates the cached server template to produce a ServerConfig.

        Args:
          context: A dictionary of values to use for evaluating conditions.

        Returns:
          A ServerConfig object.
        Raises:
            ValueError: If the input arguments are invalid.
        """
        ...
    
    def set(self, template_data_json: str): # -> None:
        """Updates the cache to store the given template is of type ServerTemplateData.

        Args:
          template_data_json: A json string representing ServerTemplateData to be cached.
        """
        ...
    
    def to_json(self): # -> str:
        """Provides the server template in a JSON format to be used for initialization later."""
        ...
    


class ServerConfig:
    """Represents a Remote Config Server Side Config."""
    def __init__(self, config_values) -> None:
        ...
    
    def get_boolean(self, key):
        """Returns the value as a boolean."""
        ...
    
    def get_string(self, key):
        """Returns the value as a string."""
        ...
    
    def get_int(self, key):
        """Returns the value as an integer."""
        ...
    
    def get_float(self, key):
        """Returns the value as a float."""
        ...
    
    def get_value_source(self, key):
        """Returns the source of the value."""
        ...
    


class _RemoteConfigService:
    """Internal class that facilitates sending requests to the Firebase Remote
        Config backend API.
    """
    def __init__(self, app) -> None:
        """Initialize a JsonHttpClient with necessary inputs.

        Args:
            app: App instance to be used for fetching app specific details required
                for initializing the http client.
        """
        ...
    
    async def get_server_template(self): # -> _ServerTemplateData:
        """Requests for a server template and converts the response to an instance of
        ServerTemplateData for storing the template parameters and conditions."""
        ...
    


class _ConditionEvaluator:
    """Internal class that facilitates sending requests to the Firebase Remote
    Config backend API."""
    def __init__(self, conditions, parameters, context, config_values) -> None:
        ...
    
    def evaluate(self): # -> Any:
        """Internal function that evaluates the cached server template to produce
        a ServerConfig"""
        ...
    
    def evaluate_conditions(self, conditions, context) -> Dict[str, bool]:
        """Evaluates a list of conditions and returns a dictionary of results.

        Args:
          conditions: A list of NamedCondition objects.
          context: An EvaluationContext object.

        Returns:
          A dictionary that maps condition names to boolean evaluation results.
        """
        ...
    
    def evaluate_condition(self, condition, context, nesting_level: int = ...) -> bool:
        """Recursively evaluates a condition.

        Args:
          condition: The condition to evaluate.
          context: An EvaluationContext object.
          nesting_level: The current recursion depth.

        Returns:
          The boolean result of the condition evaluation.
        """
        ...
    
    def evaluate_or_condition(self, or_condition, context, nesting_level: int = ...) -> bool:
        """Evaluates an OR condition.

        Args:
          or_condition: The OR condition to evaluate.
          context: An EvaluationContext object.
          nesting_level: The current recursion depth.

        Returns:
          True if any of the subconditions are true, False otherwise.
        """
        ...
    
    def evaluate_and_condition(self, and_condition, context, nesting_level: int = ...) -> bool:
        """Evaluates an AND condition.

        Args:
          and_condition: The AND condition to evaluate.
          context: An EvaluationContext object.
          nesting_level: The current recursion depth.

        Returns:
          True if all of the subconditions are met; False otherwise.
        """
        ...
    
    def evaluate_percent_condition(self, percent_condition, context) -> bool:
        """Evaluates a percent condition.

        Args:
          percent_condition: The percent condition to evaluate.
          context: An EvaluationContext object.

        Returns:
          True if the condition is met, False otherwise.
        """
        ...
    
    def hash_seeded_randomization_id(self, seeded_randomization_id: str) -> int:
        """Hashes a seeded randomization ID.

        Args:
          seeded_randomization_id: The seeded randomization ID to hash.

        Returns:
          The hashed value.
        """
        ...
    
    def evaluate_custom_signal_condition(self, custom_signal_condition, context) -> bool:
        """Evaluates a custom signal condition.

        Args:
          custom_signal_condition: The custom signal condition to evaluate.
          context: An EvaluationContext object.

        Returns:
          True if the condition is met, False otherwise.
        """
        ...
    


async def get_server_template(app: App = ..., default_config: Optional[Dict[str, str]] = ...): # -> ServerTemplate:
    """Initializes a new ServerTemplate instance and fetches the server template.

    Args:
        app: App instance to be used. This is optional and the default app instance will
            be used if not present.
        default_config: The default config to be used in the evaluated config.

    Returns:
        ServerTemplate: An object having the cached server template to be used for evaluation.
    """
    ...

def init_server_template(app: App = ..., default_config: Optional[Dict[str, str]] = ..., template_data_json: Optional[str] = ...): # -> ServerTemplate:
    """Initializes a new ServerTemplate instance.

    Args:
        app: App instance to be used. This is optional and the default app instance will
            be used if not present.
        default_config: The default config to be used in the evaluated config.
        template_data_json: An optional template data JSON to be set on initialization.

    Returns:
        ServerTemplate: A new ServerTemplate instance initialized with an optional
        template and config.
    """
    ...

class _Value:
    """Represents a value fetched from Remote Config.
    """
    DEFAULT_VALUE_FOR_BOOLEAN = ...
    DEFAULT_VALUE_FOR_STRING = ...
    DEFAULT_VALUE_FOR_INTEGER = ...
    DEFAULT_VALUE_FOR_FLOAT_NUMBER = ...
    BOOLEAN_TRUTHY_VALUES = ...
    def __init__(self, source: ValueSource, value: str = ...) -> None:
        """Initializes a Value instance.

        Args:
          source: The source of the value (e.g., 'default', 'remote', 'static').
          "static" indicates the value was defined by a static constant.
          "default" indicates the value was defined by default config.
          "remote" indicates the value was defined by config produced by evaluating a template.
          value: The string value.
        """
        ...
    
    def as_string(self) -> str:
        """Returns the value as a string."""
        ...
    
    def as_boolean(self) -> bool:
        """Returns the value as a boolean."""
        ...
    
    def as_int(self) -> float:
        """Returns the value as a number."""
        ...
    
    def as_float(self) -> float:
        """Returns the value as a number."""
        ...
    
    def get_source(self) -> ValueSource:
        """Returns the source of the value."""
        ...
    


