[project]
name = "backend"
version = "0.1.0"
requires-python = "~=3.13.0"
dependencies = [
    "gunicorn>=23",
    "firebase-admin>=7.1.0",
    "flask>=3.1.1",
    "flask-cors>=6.0.2",
    "requests>=2.32.4",
    "shared",
]

[tool.ruff.lint]
select = ["E", "F", "W"]

[tool.uv.sources]
shared = { path = "../../../shared", editable = true }
